name: 'huff-neo-toolchain'
description: 'Install huff-neo'
author: 'cakevm'
branding:
  icon: play-circle
  color: black
inputs:
  version:
    description: |
      The huff-neo version.
      This version number has to match a released version of huff-neo.
      Alternatively you can also specify `nightly` for the latest nightly build.
runs:
  using: node16
  main: dist/index.js