name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install huff-neo nightly
        uses: ./ # use huff-toolchain current commit
        with:
          version: nightly

      - name: Save huff-neo version in env for future comparison
        run: echo "HUFF_VERSION=$(huff-neo -V)" >> $GITHUB_ENV

      - name: Compile example
        run: huff-neo examples/test.huff

      - name: Install huff-neo with specific nightly
        uses: ./ # use huff-neo-toolchain current commit
        with:
          # This version was picked as it will output 0.3.0
          # Nightly and next versions outputs >= 0.3.1
          version: nightly-654207cd75a85ae3cb144eb208a2c671ee71268f

      - name: Save huffc version in env for future comparison
        run: echo "HUFF_SPECIFIC_VERSION=$(huffc -V)" >> $GITHUB_ENV

      # Compare huff-neo versions saved in GITHUB_ENV
      # If they are equal, the specific nightly version was not installed
      # In this case, print a message and fail the job by exiting
      # Otherwise, it will continue to next step
      - name: Compare version
        if: ${{ env.HUFF_SPECIFIC_VERSION == env.HUFF_VERSION }}
        run: |
          echo "specific nightly version was not installed"
          exit 1

      - name: Compile example
        run: huff-neo examples/test.huff
