name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff nightly
        uses: ./ # use huff-toolchain current commit
        with:
          version: nightly

      - name: Install Dependencies
        run: huffc examples/test.huff
